### PR TITLE
[ENH] Improve distribution tests

### LINKED ISSUE #55: [BUG] The `cdf` for the `Empirical` distribution returns a dataframe of objects
**Describe the bug**

The `cdf` function for the `Empirical` distribution returns a dataframe of python objects. It should return a dataframe of floats or integers.

**To Reproduce**

```python
>>> import pandas as pd
>>> import numpy as np
>>> from skrpo.distributions.empirical import Empirical
>>> spl_idx = pd.MultiIndex.from_product([[0, 1], [0, 1, 2]], names=["sample", "time"])
>>> spl = pd.DataFrame([[0, 1], [2, 3], [10, 11], [6, 7], [8, 9], [4, 5]], index=spl_idx, columns=["a", "b"])
>>> d = Empirical(spl)
>>> x = pd.DataFrame([[1, 2], [3, 4], [5, 6]], index=pd.Index([0, 1, 2]), columns=pd.Index(['a', 'b']))
>>> d.cdf(x)
     a    b
0  0.5  0.5
1  0.5  0.5
2  0.5  0.5
>>> d.cdf(x).values.dtype
dtype('O')
>>> d.cdf(x).dtypes
a    Float64
b    Float64
```

**Expected behavior**

The dataframe returned from `cdf` should contain floats of integers. I don't think `Float64` is a valid `pandas` datatype - it should be `float64`. Here is an example creating a simple float dataframe.

```
>>> y = pd.DataFrame([[1.0, 2.0], [3.0, 4.0]])
>>> y.dtypes
0    float64
1    float64
dtype: object
>>> y.values.dtype
dtype('float64')
```

**Environment**

Pip freeze.
```
anyio==3.7.1
backoff==2.2.1
certifi==2023.7.22
cfgv==3.4.0
coverage==7.3.0
distlib==0.3.7
exceptiongroup==1.1.3
execnet==2.0.2
filelock==3.12.2
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
identify==2.5.27
idna==3.4
iniconfig==2.0.0
joblib==1.3.2
nodeenv==1.8.0
numpy==1.24.4
packaging==23.1
pandas==2.0.3
platformdirs==3.10.0
pluggy==1.3.0
pre-commit==3.3.3
pytest==7.4.0
pytest-cov==4.1.0
pytest-randomly==3.15.0
pytest-timeout==2.1.0
pytest-xdist==3.3.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
scikit-base==0.5.1
scikit-learn==1.3.0
scipy==1.11.2
six==1.16.0
skpro @ file:///home/alex/documents/skpro
sniffio==1.3.0
threadpoolctl==3.2.0
tomli==2.0.1
tzdata==2023.3
virtualenv==20.24.3
```
OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**

This problem arose when I was trying to write a test to check if `cdf` is the inverse of `ppf`.

### PR DESCRIPTION
**Pull request by Alex-JG3**
#### Reference Issues/PRs

Closes #55, see also #21.

#### What does this implement/fix? Explain your changes.

1. Adds a test to check whether the log of the `pdf` function is similar to the `log_pdf` function for each distribution.
2. Adds a test to check that the `ppf` is the inverse of the `cdf` function. This test required the change described in 1 to use `np.allclose`.
3. Adds a test to check that `pandas`outputs of methods have all `numeric` `dtype`-s

Also fixes one instance that would have failed 2, 3:
* Changes the method for converting datatypes in the `_apply_per_ix` function of the `Empirical` distribution. Switches to use `to_numeric` instead of `convert_dtypes`.

#### Does your contribution introduce a new dependency? If yes, which one?

No

##### For all contributions
- [x] I've reviewed the project documentation on [contributing](https://skbase.readthedocs.io/en/latest/contribute.html)
- [x] I've added myself to the [list of contributors](https://github.com/sktime/skbase/blob/main/.all-contributorsrc).
- [x] The PR title starts with either [ENH], [CI/CD], [MNT], [DOC], or [BUG] indicating whether
  the PR topic is related to enhancement, CI/CD, maintenance, documentation, or a bug.

##### For code contributions
- [x] Unit tests have been added covering code functionality
- [x] Appropriate docstrings have been added (see [documentation standards](https://skbase.readthedocs.io/en/latest/contribute/development/developer_guide/creating_docs.html))
- [x] New public functionality has been added to the API Reference

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Thanks a lot!

Non-blocking change suggestions:

* I think you should add yourself to the authors field of `test_all_distrs` for this
* this does not seem to directly check the output dtypes that the change to `_apply_per_ix` fixes. Should a direct check be added to `_check_output_format`?

**Comment by fkiraly** [comment]
sorry, the failures are due to the recent upgrade of the precommit hooks, it now likes and dislikes slightly different things. Should be fixed with an update from `main`.

**Comment by fkiraly** [comment]
there´s one left, just fixing: https://github.com/sktime/skpro/pull/62

**Comment by Alex-JG3** [comment]
> Should be fixed now.

Thanks for sorting this out!

**Comment by fkiraly** [comment]
> Thanks for sorting this out!

Well, sorry for messing it up in the first place...

**Pull request merged**
