### PR TITLE
[DOC] tutorial notebook for probability distributions

### PR DESCRIPTION
**Pull request by fkiraly**
Adds a tutorial notebook for probability distributions.

Section 3 is WiP, I plan adding it later.

### CODE REVIEW

**Comment by VascoSch92** [comment]
Nice :-) Now it is super clear how distributions work.

Could you run the notebook? Such that it is also possible to see the output?

**Comment by fkiraly** [comment]
> Could you run the notebook? Such that it is also possible to see the output?

Yes, I'll do this at the end though, since I am still working on it, and don't want to commit 100 versions of each picture.

**Comment by fkiraly** [comment]
Btw, if you know how one could modify `plot` to allow plotting of multiple distributions in one place, I would be interested to hear.

Right now, if I reuse the `ax` object, it does not plot.

**Comment by VascoSch92** [comment]
> Btw, if you know how one could modify `plot` to allow plotting of multiple distributions in one place, I would be interested to hear.
> 
> Right now, if I reuse the `ax` object, it does not plot.

I will give a look

**Comment by fkiraly** [comment]
@VascoSch92, update:

* I ran the notebook now, it has images. I think I'm finished for now.
* I tried again plotting mulitple times in the `ax`, it seems to work. Bit odd, not sure why it did not worked before.

**Review by VascoSch92 — APPROVED** [review]

**Pull request merged**
