### PR TITLE
[ENH] Added Inverse Gamma distribution

### PR DESCRIPTION
**Pull request by meraldoantonio**
#### Reference Issues/PRs
Related to the development of BayesianLinearRegression class. (#358)

#### What does this implement/fix? Explain your changes.

This pull request implements the Inverse Gamma distribution  and Beta Distribution as a new distribution class. 

The Inverse Gamma implementation wraps around `scipy.stats.invgamma` to provide functionalities consistent with other distributions in the library. I introduced this distribution as the conjugate prior for the variance (σ²) of a Normal distribution for subsequent use in the `BayesianLinearRegression` class. (#358)

#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?
Correctness of implementation

#### Did you add any tests for the change?
No

#### Any other comments?
No

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

### CODE REVIEW

**Review by fkiraly — CHANGES_REQUESTED** [review]
Yes, we´ll need these for the conjugates.

Can you kindly also add these to the API reference?
`docs/source/api_reference`

**Comment by fkiraly** [comment]
also, you will need to update your fork from `main` and resolve any merge conflicts.

**Comment by meraldoantonio** [comment]
Sure! I've added the two distributions to the API reference and resolved the merged conflicts

**Comment by meraldoantonio** [comment]
I noticed a bug in the `plot` method of the Binomial. 
Screenshot 2024-06-29 at 12 41 32 PM
When I tried to plot the pmf, the resulting graph looks incorrect... (but the underlying `pmf` method shows the correct values). Will look into this

**Comment by fkiraly** [comment]
> When I tried to plot the pmf, the resulting graph looks incorrect... (but the underlying pmf method shows the correct values). I will look into this.

Yes, this is expected given the current implementation but also a bug. Could you kindly open an issue and link your example and add my comments below?

Currently, the plotting function sampes a grid of x points, plots x, f(x) for the function and connects them. If the grid does not hit the mass points, the plot will look like this.

The only way to have the correct pot is to know where the support is. That is currenty not inspectable, and that's why I wanted the sets symbolism from #244..

Speaking of which, do you have an ETA for the next iteration, or are you no longer working on this, @vascosch92? Any response is fine, just for planning.

**Review by fkiraly — CHANGES_REQUESTED** [review]
import in docstring example fails due to wrong module name

**Comment by meraldoantonio** [comment]
Sorry about that - have fixed the docstring typo

**Comment by meraldoantonio** [comment]
Also, have opened a new issue about the plot pmf bug #416

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
