### PR TITLE
[MNT] `Exponential` dist in `NGBoostRegressor`, `NGBoostSurvival`

### PR DESCRIPTION
**Pull request by ShreeshaM07**
#### What does this implement/fix? Explain your changes.

This adds exponential distribution to `NGBoostRegressor` and `NGBoostSurvival`.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Did you add any tests for the change?

Yes

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

### CODE REVIEW

**Review by fkiraly — APPROVED** [review]
Nice!

I think we can merge like this, but I am noticing a duplication in `_predict_proba`, namely the logic to translate `ngboost` distirbution parameters to `skpro` distribution parameters is duplicated. How about moving these into the adapter, too, to have only one location?

Not a blocker, let me know if you would like to do it in tihs PR, another one, or not at all.

**Comment by ShreeshaM07** [comment]
I have moved most of the common code to the adapter now I hope that looks fine.

**Comment by fkiraly** [comment]
> I have moved most of the common code to the adapter now I hope that looks fine.

The way I'd do it, I'd remove the dependency on `X` and calls of `self._pred_dict`, and instead have `index`, `columns` as args.

**Comment by fkiraly** [comment]
That's what I meant, excellent!

**Comment by ShreeshaM07** [comment]
> The way I'd do it, I'd remove the dependency on `X` and calls of `self._pred_dict`, and instead have `index`, `columns` as args, as well as the return of `_pred_dict`.

Yeah that makes more sense.

**Review by fkiraly — APPROVED** [review]

**Pull request merged**
